name: CI

on:
  push:
    paths-ignore:
      - 'openapi/**'
      - '**.md'
    branches:
      - main
      - 'release/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-20.04
    env:
      DOCKER_REGISTRY_URL: tip-tip-wlan-cloud-ucentral.jfrog.io
      DOCKER_REGISTRY_USERNAME: ucentral
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t wlan-cloud-owprov:${{ github.sha }} .

    - name: Tag Docker image
      run: |
        TAGS="${{ github.sha }}"
        if [[ ${GITHUB_REF} == "refs/heads/"* ]]
        then
          CURRENT_TAG=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
          TAGS="$TAGS $CURRENT_TAG"
        else
          if [[ ${GITHUB_REF} == "refs/tags/"* ]]
          then
            CURRENT_TAG=$(echo ${GITHUB_REF#refs/tags/} | tr '/' '-')
            TAGS="$TAGS $CURRENT_TAG"
          else # PR build
            CURRENT_TAG=$(echo ${GITHUB_HEAD_REF#refs/heads/} | tr '/' '-')
            TAGS="$TAGS $CURRENT_TAG"
          fi
        fi
        echo "Result tags: $TAGS"
        for tag in $TAGS; do
          docker tag wlan-cloud-owprov:${{ github.sha }} ${{ env.DOCKER_REGISTRY_URL }}/owprov:$tag
        done
    - name: Log into Docker registry
      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/pull/') || github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY_URL }}
        username: ${{ env.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Push Docker images
      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/pull/') || github.ref == 'refs/heads/main'
      run: |
        docker images | grep ${{ env.DOCKER_REGISTRY_URL }}/owprov | awk -F ' ' '{print $1":"$2}' | xargs -I {} docker push {}

  trigger-testing:
    if: startsWith(github.ref, 'refs/pull/')
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Get base branch name and set as output
      id: get_base_branch
      run: |
        echo ::set-output name=branch::$(echo ${GITHUB_BASE_REF##*/})
        echo ::set-output name=owgw_branch::$(echo ${GITHUB_BASE_REF##*/} | sed 's/main/master/g')

    - name: Checkout actions repo
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/.github
        path: github

    - name: Trigger testing of OpenWifi Docker Compose deployment and wait for result
      uses: ./github/composite-actions/trigger-workflow-and-wait
      env:
        BASE_BRANCH: ${{ steps.get_base_branch.outputs.branch }}
        OWGW_BASE_BRANCH: ${{ steps.get_base_branch.outputs.owgw_branch }}
      with:
        owner: Telecominfraproject
        repo: wlan-testing
        workflow: ow_docker-compose.yml
        token: ${{ secrets.WLAN_TESTING_PAT }}
        ref: master
        inputs: '{"owgw_version": "${{ env.OWGW_BASE_BRANCH }}", "owgwui_version": "${{ env.BASE_BRANCH }}", "owsec_version": "${{ env.BASE_BRANCH }}", "owfms_version": "${{ env.BASE_BRANCH }}", "owprov_version": "${{ github.sha }}", "owprovui_version": "${{ env.BASE_BRANCH }}"}'
